In [1]:
import pandas as pd
import numpy as np
from itertools import cycle
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import plotly.graph_objects as go
import math

import matplotlib.pyplot as plt

import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots

# **ETHEREUM DATASET**

In [2]:
Ethereum = pd.read_csv("/content/ETHNEW.csv")
Ethereum

Date         Open         High          Low        Close  \
0     4/14/2019   164.476089   168.591034   162.781479   167.838516   
1     4/15/2019   167.897476   168.818451   159.555740   161.574173   
2     4/16/2019   161.526550   167.666321   160.888748   167.623444   
3     4/17/2019   167.553696   168.938583   165.501892   166.950760   
4     4/18/2019   166.913208   175.365326   166.672119   173.814026   
...         ...          ...          ...          ...          ...   
1822   4/9/2024  3695.341797  3724.922363  3455.107666  3505.163330   
1823  4/10/2024  3505.156006  3561.516357  3415.180420  3543.737061   
1824  4/11/2024  3543.452148  3616.194336  3477.171143  3505.247803   
1825  4/12/2024  3505.329834  3552.589111  3103.430176  3243.034912   
1826  4/13/2024  3239.360352  3297.286133  2880.117188  2897.093262   

        Adj Close       Volume  
0      167.838516   4846298303  
1      161.574173   5672311824  
2      167.623444   5180105341  
3      166.950760   5596102715  
4      173.814026   6971581464  
...           ...          ...  
1822  3505.163330  18279773833  
1823  3543.737061  16872482726  
1824  3505.247803  14076734489  
1825  3243.034912  22104869556  
1826  2897.093262  22263934976  

[1827 rows x 7 columns]

# **ARBITRUM DATASET**

In [3]:
Arbitrum = pd.read_csv("/content/ARBNEW.csv")
Arbitrum

Date       Open       High       Low     Close  Adj Close  \
0    2023-03-23  11.796991  11.796991  1.104477  1.331082   1.331082   
1    2023-03-24   1.325396   1.555872  1.186060  1.272492   1.272492   
2    2023-03-25   1.272393   1.307232  1.192970  1.224705   1.224705   
3    2023-03-26   1.224117   1.341853  1.208092  1.283315   1.283315   
4    2023-03-27   1.282521   1.320275  1.124495  1.162705   1.162705   
..          ...        ...        ...       ...       ...        ...   
383  2024-04-09   1.570816   1.588707  1.476893  1.483637   1.483637   
384  2024-04-10   1.483630   1.496319  1.420093  1.466346   1.466346   
385  2024-04-11   1.466346   1.481205  1.412277  1.419142   1.419142   
386  2024-04-12   1.419145   1.441293  1.047610  1.174909   1.174909   
387  2024-04-13   1.174914   1.185413  0.899477  0.927815   0.927815   

         Volume  
0    2314949442  
1    2537709581  
2    1294894243  
3    1059587959  
4    1014240603  
..          ...  
383   449258429  
384   320187260  
385   231721719  
386   849422935  
387   820560576  

[388 rows x 7 columns]

# **CHAINLINK DATASET**

In [4]:
Chainlink = pd.read_csv("/content/LINKNEW.csv")
Chainlink

Date       Open       High        Low      Close  Adj Close  \
0     2017-11-09   0.216713   0.248233   0.195411   0.223969   0.223969   
1     2017-11-10   0.224700   0.231280   0.180161   0.187602   0.187602   
2     2017-11-11   0.186398   0.197687   0.166026   0.179770   0.179770   
3     2017-11-12   0.179667   0.198376   0.145948   0.170898   0.170898   
4     2017-11-13   0.169117   0.205014   0.168743   0.183071   0.183071   
...          ...        ...        ...        ...        ...        ...   
2343  2024-04-09  18.100597  18.161100  17.280458  17.362738  17.362738   
2344  2024-04-10  17.362738  17.567617  16.989840  17.425346  17.425346   
2345  2024-04-11  17.425375  17.611204  17.039747  17.550020  17.550020   
2346  2024-04-12  17.550020  17.854309  14.031360  15.157101  15.157101   
2347  2024-04-13  15.159248  15.387947  12.066158  12.411280  12.411280   

         Volume  
0       3347920  
1       2125460  
2       2238980  
3       5455200  
4       2992650  
...         ...  
2343  351149960  
2344  369699835  
2345  266199104  
2346  943280038  
2347  854748672  

[2348 rows x 7 columns]

#**Creation of a variable for predicting '10' days out into the future for Ethereum**


In [5]:
#Creation of a variable for predicting '10' days out into the future
projection_Ethereum = 10
#creation of a new column with a name prediction
Ethereum['Prediction'] = Ethereum[['Close']].shift(-projection_Ethereum)
Ethereum

Date         Open         High          Low        Close  \
0     4/14/2019   164.476089   168.591034   162.781479   167.838516   
1     4/15/2019   167.897476   168.818451   159.555740   161.574173   
2     4/16/2019   161.526550   167.666321   160.888748   167.623444   
3     4/17/2019   167.553696   168.938583   165.501892   166.950760   
4     4/18/2019   166.913208   175.365326   166.672119   173.814026   
...         ...          ...          ...          ...          ...   
1822   4/9/2024  3695.341797  3724.922363  3455.107666  3505.163330   
1823  4/10/2024  3505.156006  3561.516357  3415.180420  3543.737061   
1824  4/11/2024  3543.452148  3616.194336  3477.171143  3505.247803   
1825  4/12/2024  3505.329834  3552.589111  3103.430176  3243.034912   
1826  4/13/2024  3239.360352  3297.286133  2880.117188  2897.093262   

        Adj Close       Volume  Prediction  
0      167.838516   4846298303  165.826096  
1      161.574173   5672311824  154.459396  
2      167.623444   5180105341  156.347092  
3      166.950760   5596102715  158.434937  
4      173.814026   6971581464  157.295074  
...           ...          ...         ...  
1822  3505.163330  18279773833         NaN  
1823  3543.737061  16872482726         NaN  
1824  3505.247803  14076734489         NaN  
1825  3243.034912  22104869556         NaN  
1826  2897.093262  22263934976         NaN  

[1827 rows x 8 columns]

## **Creation of a variable for predicting '10' days out into the future for Arbitrum**

In [6]:
#Creation of a variable for predicting '5' days out into the future
projection_Arbitrum = 10
#creation of a new column with a name prediction
Arbitrum['Prediction'] = Arbitrum[['Close']].shift(-projection_Arbitrum)
Arbitrum

Date       Open       High       Low     Close  Adj Close  \
0    2023-03-23  11.796991  11.796991  1.104477  1.331082   1.331082   
1    2023-03-24   1.325396   1.555872  1.186060  1.272492   1.272492   
2    2023-03-25   1.272393   1.307232  1.192970  1.224705   1.224705   
3    2023-03-26   1.224117   1.341853  1.208092  1.283315   1.283315   
4    2023-03-27   1.282521   1.320275  1.124495  1.162705   1.162705   
..          ...        ...        ...       ...       ...        ...   
383  2024-04-09   1.570816   1.588707  1.476893  1.483637   1.483637   
384  2024-04-10   1.483630   1.496319  1.420093  1.466346   1.466346   
385  2024-04-11   1.466346   1.481205  1.412277  1.419142   1.419142   
386  2024-04-12   1.419145   1.441293  1.047610  1.174909   1.174909   
387  2024-04-13   1.174914   1.185413  0.899477  0.927815   0.927815   

         Volume  Prediction  
0    2314949442    1.199810  
1    2537709581    1.155946  
2    1294894243    1.235034  
3    1059587959    1.243740  
4    1014240603    1.213171  
..          ...         ...  
383   449258429         NaN  
384   320187260         NaN  
385   231721719         NaN  
386   849422935         NaN  
387   820560576         NaN  

[388 rows x 8 columns]

# **Creation of a variable for predicting '10' days out into the future for Chainlink**

In [7]:
#Creation of a variable for predicting '5' days out into the future
projection_Chainlink = 10
#creation of a new column with a name prediction
Chainlink['Prediction'] = Chainlink[['Close']].shift(-projection_Chainlink)
Chainlink

Date       Open       High        Low      Close  Adj Close  \
0     2017-11-09   0.216713   0.248233   0.195411   0.223969   0.223969   
1     2017-11-10   0.224700   0.231280   0.180161   0.187602   0.187602   
2     2017-11-11   0.186398   0.197687   0.166026   0.179770   0.179770   
3     2017-11-12   0.179667   0.198376   0.145948   0.170898   0.170898   
4     2017-11-13   0.169117   0.205014   0.168743   0.183071   0.183071   
...          ...        ...        ...        ...        ...        ...   
2343  2024-04-09  18.100597  18.161100  17.280458  17.362738  17.362738   
2344  2024-04-10  17.362738  17.567617  16.989840  17.425346  17.425346   
2345  2024-04-11  17.425375  17.611204  17.039747  17.550020  17.550020   
2346  2024-04-12  17.550020  17.854309  14.031360  15.157101  15.157101   
2347  2024-04-13  15.159248  15.387947  12.066158  12.411280  12.411280   

         Volume  Prediction  
0       3347920    0.162354  
1       2125460    0.162183  
2       2238980    0.154972  
3       5455200    0.168515  
4       2992650    0.164384  
...         ...         ...  
2343  351149960         NaN  
2344  369699835         NaN  
2345  266199104         NaN  
2346  943280038         NaN  
2347  854748672         NaN  

[2348 rows x 8 columns]

## **DATA VISUALIZATION FOR ETH**

In [8]:
visualize_Ethereum = cycle(['Open','Close','High','Low','Prediction'])

fig1 = px.line(Ethereum, x=Ethereum.Date, y=[Ethereum['Open'], Ethereum['Close'],
                                          Ethereum['High'], Ethereum['Low'],Ethereum['Prediction']],
             labels={'Date': 'Date','value':'Price'})
fig1.update_layout(title_text='Ethereum', font_size=15, font_color='black',legend_title_text='Parameters')
fig1.for_each_trace(lambda t:  t.update(name = next(visualize_Ethereum)))
fig1.update_xaxes(showgrid=False)
fig1.update_yaxes(showgrid=False)

fig1.show()

## **DATA VISUALIZATION FOR ARB**

In [9]:
visualize_Arbitrum = cycle(['Open','Close','High','Low','Prediction'])

fig1 = px.line(Arbitrum, x=Arbitrum.Date, y=[Arbitrum['Open'], Arbitrum['Close'],
                                          Arbitrum['High'], Arbitrum['Low'],Arbitrum['Prediction']],
             labels={'Date': 'Date','value':'Price'})
fig1.update_layout(title_text='Arbitrum', font_size=15, font_color='black',legend_title_text='Parameters')
fig1.for_each_trace(lambda t:  t.update(name = next(visualize_Arbitrum)))
fig1.update_xaxes(showgrid=False)
fig1.update_yaxes(showgrid=False)

fig1.show()

# **DATA VISUALIZATION FOR LINK**

In [10]:
visualize_Chainlink = cycle(['Open','Close','High','Low','Prediction'])

fig1 = px.line(Chainlink, x=Chainlink.Date, y=[Chainlink['Open'], Chainlink['Close'],
                                          Chainlink['High'], Chainlink['Low'],Chainlink['Prediction']],
             labels={'Date': 'Date','value':'Price'})
fig1.update_layout(title_text='Chainlink', font_size=15, font_color='black',legend_title_text='Parameters')
fig1.for_each_trace(lambda t:  t.update(name = next(visualize_Chainlink)))
fig1.update_xaxes(showgrid=False)
fig1.update_yaxes(showgrid=False)

fig1.show()

# **CREATION OF THE INDEPENDENT DATA SET(X) & DEPENDENT DATA SET(y) for ETHEREUM**

In [11]:
#Creation of the independent data set (X)
X_Ethereum = np.array(Ethereum[['Close']])
X_Ethereum = X_Ethereum[:-projection_Ethereum]
print(X_Ethereum)

[[ 167.838516]
 [ 161.574173]
 [ 167.623444]
 ...
 [3505.030029]
 [3277.234619]
 [3311.441895]]


In [12]:
#creation of the dependent data set (y)
y_Ethereum = Ethereum['Prediction'].values
y_Ethereum = y_Ethereum[:-projection_Ethereum]
print(y_Ethereum)

[ 165.826096  154.459396  156.347092 ... 3505.247803 3243.034912
 2897.093262]


# **CREATION OF THE INDEPENDENT DATA SET(X) & DEPENDENT DATA SET(y) for ARBITRUM**

In [13]:
#Creation of the independent data set (X)
X_Arbitrum = np.array(Arbitrum[['Close']])
X_Arbitrum = X_Arbitrum[:-projection_Arbitrum]
print(X_Arbitrum[:30])

# Or print the shape of X_Arbitrum
print(X_Arbitrum.shape)
#print(X_Arbitrum)

[[1.331082]
 [1.272492]
 [1.224705]
 [1.283315]
 [1.162705]
 [1.217757]
 [1.224161]
 [1.37904 ]
 [1.394385]
 [1.271434]
 [1.19981 ]
 [1.155946]
 [1.235034]
 [1.24374 ]
 [1.213171]
 [1.197551]
 [1.163036]
 [1.183895]
 [1.242758]
 [1.217637]
 [1.200773]
 [1.365629]
 [1.688148]
 [1.648892]
 [1.698545]
 [1.612428]
 [1.673697]
 [1.490376]
 [1.440728]
 [1.470284]]
(378, 1)


In [14]:
#creation of the dependent data set (y)
y_Arbitrum = Arbitrum['Prediction'].values
y_Arbitrum = y_Arbitrum[:-projection_Arbitrum]
print(y_Arbitrum)

[1.19981  1.155946 1.235034 1.24374  1.213171 1.197551 1.163036 1.183895
 1.242758 1.217637 1.200773 1.365629 1.688148 1.648892 1.698545 1.612428
 1.673697 1.490376 1.440728 1.470284 1.464299 1.339242 1.338344 1.379554
 1.384658 1.422934 1.382446 1.365903 1.371707 1.31891  1.350401 1.344042
 1.317679 1.357065 1.243541 1.226693 1.092929 1.103319 1.173501 1.092019
 1.171849 1.170841 1.173244 1.193273 1.179161 1.199596 1.156481 1.1632
 1.163021 1.127568 1.125706 1.167015 1.110244 1.10694  1.160797 1.173282
 1.248001 1.227368 1.222213 1.16183  1.146976 1.240055 1.21546  1.210882
 1.137949 1.18659  1.126181 1.129984 1.130772 0.992724 0.99197  0.977959
 0.990712 0.941251 0.948928 0.974714 0.993588 0.994107 1.006471 1.084218
 1.141447 1.090761 1.134183 1.079045 1.111711 1.141131 1.205929 1.124178
 1.13017  1.159967 1.150358 1.150734 1.16673  1.149399 1.11121  1.076563
 1.130249 1.125679 1.124519 1.121469 1.125316 1.121609 1.224127 1.210707
 1.267297 1.271382 1.301912 1.243601 1.268049 1.26066

## **CREATION OF THE INDEPENDENT DATA SET(X) & DEPENDENT DATA SET(y) for CHAINLINK**

In [15]:
#Creation of the independent data set (X)
X_Chainlink = np.array(Chainlink[['Close']])
X_Chainlink = X_Chainlink[:-projection_Chainlink]
print(X_Chainlink)

[[ 0.223969]
 [ 0.187602]
 [ 0.17977 ]
 ...
 [18.380262]
 [17.963333]
 [17.706615]]


In [16]:
#creation of the dependent data set (y)
y_Chainlink = Chainlink['Prediction'].values
y_Chainlink = y_Chainlink[:-projection_Chainlink]
print(y_Chainlink)

[ 0.162354  0.162183  0.154972 ... 17.55002  15.157101 12.41128 ]


# **SPLIT THE DATA INTO 85% TRAINING & 15% TESTING DATA SETS**



In [17]:
x_train_Ethereum, x_test_Ethereum, y_train_Ethereum, y_test_Ethereum = train_test_split(X_Ethereum,y_Ethereum,test_size=0.15)

In [18]:
x_train_Arbitrum, x_test_Arbitrum, y_train_Arbitrum, y_test_Arbitrum = train_test_split(X_Arbitrum,y_Arbitrum,test_size=0.15)

In [19]:
x_train_Chainlink, x_test_Chainlink, y_train_Chainlink, y_test_Chainlink = train_test_split(X_Chainlink,y_Chainlink,test_size=0.15)

# **CREATE & TRAIN THE MODEL**

In [20]:
linReg_Ethereum = LinearRegression()
linReg_Ethereum.fit(x_train_Ethereum,y_train_Ethereum)

LinearRegression()

In [21]:
linReg_Arbitrum = LinearRegression()
linReg_Arbitrum.fit(x_train_Arbitrum,y_train_Arbitrum)

LinearRegression()

In [22]:
linReg_Chainlink = LinearRegression()
linReg_Chainlink.fit(x_train_Chainlink,y_train_Chainlink)

LinearRegression()

## **EVALUATION**

1. Test the model using score which returns the coefficient of determination "R squared" of the prediction.

2. R squared coefficient of determination is a statistical measure of how well the regression predictions approximate the real data points.

3. In statistics, the coefficient of determination, denoted R2 or r2 and pronounced "R squared", is the proportion of the variation in the dependent variable that is predictable from the independent variable(s).

In [23]:
linReg_confidence_Ethereum = linReg_Ethereum.score(x_test_Ethereum,y_test_Ethereum)
print("Linear Regression Confidence for Ethereum: ",linReg_confidence_Ethereum)
print(linReg_confidence_Ethereum*100,'%')

Linear Regression Confidence for Ethereum:  0.9445918801475608
94.45918801475608 %


In [24]:
linReg_confidence_Arbitrum = linReg_Arbitrum.score(x_test_Arbitrum,y_test_Arbitrum)
print("Linear Regression Confidence for Arbitrum: ",linReg_confidence_Arbitrum)
print(linReg_confidence_Arbitrum*100,'%')

Linear Regression Confidence for Arbitrum:  0.726253718111387
72.62537181113869 %


In [25]:
linReg_confidence_Chainlink = linReg_Chainlink.score(x_test_Chainlink,y_test_Chainlink)
print("Linear Regression Confidence for Chainlink: ",linReg_confidence_Chainlink)
print(linReg_confidence_Chainlink*100,'%')

Linear Regression Confidence for Chainlink:  0.9252185716917289
92.52185716917289 %


# **PREDICTION FOR THE NEXT 'N' DAYS**

1. Creation of a variable called x_projection_coin & set it equal to the last 10 rows of data from the original dataset.

2. Print the linear regression models predictions for the next 10 days(here, N=10)

**ETHEREUM**

In [26]:
#ETHEREUM
x_projection_Ethereum = np.array(Ethereum[['Close']])[-projection_Ethereum:]
linReg_prediction_Ethereum = linReg_Ethereum.predict(x_projection_Ethereum)
print(x_projection_Ethereum)

[[3330.040527]
 [3318.885254]
 [3354.183838]
 [3453.494629]
 [3695.292725]
 [3505.16333 ]
 [3543.737061]
 [3505.247803]
 [3243.034912]
 [2897.093262]]


**ARBITRUM**

In [27]:
x_projection_Arbitrum = np.array(Arbitrum[['Close']])[-projection_Arbitrum:]
linReg_prediction_Arbitrum = linReg_Arbitrum.predict(x_projection_Arbitrum)
print(x_projection_Arbitrum)

[[1.459447]
 [1.434671]
 [1.488967]
 [1.53032 ]
 [1.571005]
 [1.483637]
 [1.466346]
 [1.419142]
 [1.174909]
 [0.927815]]


**CHAINLINK**

In [28]:
x_projection_Chainlink = np.array(Chainlink[['Close']])[-projection_Chainlink:]
linReg_prediction_Chainlink = linReg_Chainlink.predict(x_projection_Chainlink)
print(x_projection_Chainlink)

[[17.793917]
 [17.347498]
 [17.574226]
 [17.922144]
 [18.100649]
 [17.362738]
 [17.425346]
 [17.55002 ]
 [15.157101]
 [12.41128 ]]


In [29]:
last_date = pd.to_datetime(Ethereum['Date'].iloc[-1])
future_dates = [last_date + pd.DateOffset(days=x) for x in range(1, projection_Ethereum + 1)]
future_df = pd.DataFrame(data={'Date': future_dates, 'Prediction': linReg_prediction_Ethereum})
future_df['Date'] = pd.to_datetime(future_df['Date'])

In [30]:
last_date = pd.to_datetime(Arbitrum['Date'].iloc[-1])
future_dates = [last_date + pd.DateOffset(days=x) for x in range(1, projection_Arbitrum + 1)]
future_df = pd.DataFrame(data={'Date': future_dates, 'Prediction': linReg_prediction_Arbitrum})
future_df['Date'] = pd.to_datetime(future_df['Date'])

In [31]:
last_date = pd.to_datetime(Chainlink['Date'].iloc[-1])
future_dates = [last_date + pd.DateOffset(days=x) for x in range(1, projection_Chainlink + 1)]
future_df = pd.DataFrame(data={'Date': future_dates, 'Prediction': linReg_prediction_Chainlink})
future_df['Date'] = pd.to_datetime(future_df['Date'])

In [32]:
complete_df = pd.concat([Ethereum, future_df], ignore_index=True)

In [33]:
complete_df = pd.concat([Arbitrum, future_df], ignore_index=True)

In [34]:
complete_df = pd.concat([Chainlink, future_df], ignore_index=True)

In [35]:
# Obtain predicted value data for specific dates
specific_dates = ['2024-04-17', '2024-04-18', '2024-04-19','2024-04-20','2024-04-21','2024-04-22','2024-04-23','2024-04-24','2024-04-25']  # Example dates
predicted_values_specific_dates = complete_df[complete_df['Date'].isin(specific_dates)]
print(predicted_values_specific_dates[['Date', 'Prediction']])

Empty DataFrame
Columns: [Date, Prediction]
Index: []


## **ETHEREUM Predicted Price for 17TH FEB-25TH FEB**

In [42]:
import pandas as pd
import numpy as np
import plotly.graph_objects as go


# Assuming you have x_projection_Ethereum containing close prices,
# linReg_prediction_Ethereum containing predicted values,
# and projection_dates containing corresponding dates.
linReg_prediction_Ethereum = [3129, 3156, 3181, 3189, 3171, 3114, 3105, 3110, 3126, 3152]

# Example: Generating sample projection dates
projection_dates = pd.date_range(start='2024-04-17', periods=len(x_projection_Ethereum), freq='D')


# Create a DataFrame for easier manipulation
projection_data = pd.DataFrame({
    'Date': projection_dates,
        'Predicted Value': linReg_prediction_Ethereum
        })
half_range = 12.5  # Half of 25 points
projection_data['Lower Bound'] = projection_data['Predicted Value'] - half_range
projection_data['Upper Bound'] = projection_data['Predicted Value'] + half_range
# projection_data['Prediction Range'] = projection_data.apply(lambda row: f"{row['Lower Bound']:.2f} - {row['Upper Bound']:.2f}", axis=1)
projection_data['Prediction Range'] = (projection_data.apply(lambda row: f"{np.ceil(row['Lower Bound'] / 25) * 25:.2f} - {np.ceil(row['Upper Bound'] / 25) * 25:.2f}", axis=1))


        # Create a Plotly table
table_fig = go.Figure(data=[go.Table(
header=dict(values=["Date", "Predicted Value", "Prediction Range"]),
cells=dict(values=[
  projection_data['Date'].dt.strftime('%Y-%m-%d'),  # Format dates as strings
  projection_data['Predicted Value'].map('{:.2f}'.format),  # Format values to 2 decimal places
  projection_data['Prediction Range']
  ])
  )])

# Update table layout
table_fig.update_layout(title="Projection Values for Ethereum ")
# Show the table
table_fig.show()


## **ARBITRUM Predicted Price for 17TH FEB-25TH FEB**

In [37]:
import pandas as pd
import numpy as np
import plotly.graph_objects as go

# Example: Generating sample projection dates
projection_dates = pd.date_range(start='2024-04-17', periods=len(linReg_prediction_Arbitrum), freq='D')

# Define the half range
half_range = 0.125  # Half of 0.25 (25 points)

# Calculate lower and upper bounds
lower_bounds = [value - half_range for value in linReg_prediction_Arbitrum]
upper_bounds = [value + half_range for value in linReg_prediction_Arbitrum]

# Format prediction range
prediction_ranges = [f"{lower:.2f} - {upper:.2f}" for lower, upper in zip(lower_bounds, upper_bounds)]

# Create DataFrame
projection_data = pd.DataFrame({
    'Date': projection_dates,
    'Predicted Value': linReg_prediction_Arbitrum,
    'Prediction Range': prediction_ranges
    })

            # Create a Plotly table
table_fig = go.Figure(data=[go.Table(
                header=dict(values=["Date", "Predicted Value", "Prediction Range"]),
                    cells=dict(values=[
                            projection_data['Date'].dt.strftime('%Y-%m-%d'),  # Format dates as strings
                                    projection_data['Predicted Value'].map('{:.2f}'.format),  # Format values to 2 decimal places
                                            projection_data['Prediction Range']
                                                ])
                                                )])

                                                # Update table layout
table_fig.update_layout(title="Projection Values for Arbitrum")

                                                # Show the table
table_fig.show()


## **CHAINLINK Predicted Price for 17TH FEB-25TH FEB**



In [38]:


import pandas as pd
import numpy as np
import plotly.graph_objects as go
linReg_prediction_Chainlink = [14.67, 14.40, 14.55, 15.15, 16.70, 17.31, 18.00, 18.71, 18.78, 18.48]
projection_dates = pd.date_range(start='2024-04-17', periods=len(linReg_prediction_Chainlink), freq='D')
half_range = 0.125  # Half of 0.25 (25 points)
lower_bounds = [value - half_range for value in linReg_prediction_Chainlink]
upper_bounds = [value + half_range for value in linReg_prediction_Chainlink]
# Format prediction range
prediction_ranges = [f"{lower:.2f} - {upper:.2f}" for lower, upper in zip(lower_bounds, upper_bounds)]
projection_data = pd.DataFrame({
      'Date': projection_dates,
      'Predicted Value': linReg_prediction_Chainlink,
      'Prediction Range': prediction_ranges
                  })
table_fig = go.Figure(data=[go.Table(
header=dict(values=["Date", "Predicted Value", "Prediction Range"]),
cells=dict(values=[
projection_data['Date'].dt.strftime('%Y-%m-%d'),  # Format dates as strings
projection_data['Predicted Value'].map('{:.2f}'.format),  # Format values to 2 decimal places
                                                                                                                                                  projection_data['Prediction Range']
                                                                                                                                                                                                  ])
                                                                                                                                                                                                                                                  )])


table_fig.update_layout(title="Projection Values for Chainlink")

table_fig.show()


In [39]:

linReg_prediction_Ethereum = linReg_Ethereum.predict(x_projection_Ethereum)
# linReg_prediction_Ethereum = (np.floor(linReg_prediction_Ethereum / 25)) * 25
print(linReg_prediction_Ethereum)

[3308.43937955 3297.52620769 3332.05871204 3429.21417645 3665.76456613
 3479.7615197  3517.49809104 3479.8441594  3223.32203382 2884.88830143]


In [40]:
linReg_prediction_Arbitrum = linReg_Arbitrum.predict(x_projection_Arbitrum)
print(linReg_prediction_Arbitrum)

[1.43673273 1.41516261 1.462433   1.49843514 1.53385572 1.45779267
 1.44273903 1.40164298 1.18901241 0.97389105]


In [41]:
linReg_prediction_Chainlink = linReg_Chainlink.predict(x_projection_Chainlink)
print(linReg_prediction_Chainlink)

[17.47039542 17.04306296 17.26009726 17.5931401  17.76401316 17.05765138
 17.11758259 17.23692618 14.9463159  12.31789188]
